### ISSUE TITLE
In-app browser crashes after rotation

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#1041]
If I have an article open in the in-app browser and rotate my phone to landscape mode then rotate back to portrait mode, the application crashes 100% of the time.
I am using the Pixel 2 on Android 8.1.0, although this happened on older OS versions as well.
I usually use chrome, I also have edge installed to check it out.

This could be tied to a crash with Chrome webview that started to pike up end of January.

<details>

```
Caused by java.lang.IllegalArgumentException: Receiver not registered: org.chromium.content.browser.accessibility.LollipopWebContentsAccessibility$1@a52cb27
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1054)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1376)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:668)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:668)
       at org.chromium.content.browser.accessibility.LollipopWebContentsAccessibility.onDetachedFromWindow(LollipopWebContentsAccessibility.java:42)
       at org.chromium.content.browser.ContentViewCoreImpl.onDetachedFromWindow(ContentViewCoreImpl.java:339)
       at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDetachedFromWindow(AwContents.java:351)
       at org.chromium.android_webview.AwContents.onDetachedFromWindow(AwContents.java:598)
       at com.android.webview.chromium.WebViewChromium.onDetachedFromWindow(WebViewChromium.java:802)
       at android.webkit.WebView.onDetachedFromWindowInternal(WebView.java:2365)
       at android.view.View.dispatchDetachedFromWindow(View.java:16782)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3429)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3421)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3421)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3421)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3421)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4959)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4933)
       at android.view.ViewGroup.removeView(ViewGroup.java:4864)
       at android.support.v4.view.ViewPager.removeView(ViewPager.java:1501)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1520)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3218)
       at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:262)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:362)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
       at io.github.hidroh.materialistic.ThemedActivity.onDestroy(ThemedActivity.java:76)
       at io.github.hidroh.materialistic.InjectableActivity.onDestroy(InjectableActivity.java:37)
       at io.github.hidroh.materialistic.ItemActivity.onDestroy(ItemActivity.java:246)
       at android.app.Activity.performDestroy(Activity.java:7208)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4954)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
</details>

![screenshot_20180207-145933](https://user-images.githubusercontent.com/1978015/35914116-fdeb9b22-0bf9-11e8-9809-90ada2232ef6.png)

**Comment by hidroh** [comment]
Seems to be fixed externally by https://chromium.googlesource.com/chromium/src/+/8839385d34f511f6498bc20edba638944b67d0cd
