### ISSUE TITLE
Rotating the screen before selecting "zoom in or zoom out" causes a crash

### ISSUE THREAD

**Issue by jyjsunny** [hidroh/materialistic#1463]
**Describe the bug**
Rotating the screen before selecting "zoom in or zoom out" causes a crash

**To Reproduce**
1. Click one story
2. Click the red button in the bottom right corner
3. Click on the three dots in the upper right corner
4. Rotate the screen counterclockwise before selecting "zoom in" or "zoom out".
5. Rotate the screen clockwise
6. See error

**Video**

https://user-images.githubusercontent.com/92309998/170476827-fef81873-4cf5-4a4a-9607-858b061d050a.mov

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S9]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 0.84]

**bug trace**
: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
: 	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:484)
: 	at android.app.assist.AssistStructure.<init>(AssistStructure.java:1908)
: 	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3035)
: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1807)
: 	at android.os.Handler.dispatchMessage(Handler.java:105)
: 	at android.os.Looper.loop(Looper.java:164)
: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
: 	at java.lang.reflect.Method.invoke(Native Method)
: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by jyjsunny** [comment]
@astashov Hello, Could I ask about the current status of this issue?

Looking forward to your reply!

**Comment by jyjsunny** [comment]
@astashov @noloman @jaredsburrows @hidroh Hello, Could I ask about the current status of this issue?

Looking forward to your reply!
