### ISSUE TITLE
Should not call Context.getResources() when detached

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#311]
Version 42.
```
Fatal Exception: java.lang.IllegalStateException: Fragment ItemFragment{2d57df8b} not attached to Activity
       at android.support.v4.app.Fragment.getResources(Fragment.java:639)
       at io.github.hidroh.materialistic.ItemFragment.onCreateOptionsMenu(ItemFragment.java:154)
       at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2044)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2114)
       at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:270)
       at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:299)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:549)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by hidroh** [comment]
```
Fatal Exception: java.lang.IllegalStateException: Fragment ReadabilityFragment{36ef4016} not attached to Activity
       at android.support.v4.app.Fragment.getResources(Fragment.java:639)
       at io.github.hidroh.materialistic.ReadabilityFragment.onCreateOptionsMenu(ReadabilityFragment.java:90)
       at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2044)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2114)
       at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:270)
       at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:299)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:549)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5389)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```
