### ISSUE TITLE
Activity.onBackPressed caused IllegalStateException

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#317]
Version 42.
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:584)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:169)
       at android.app.Activity.onKeyUp(Activity.java:2237)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2674)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2467)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2045)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4022)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3996)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3499)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3499)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3575)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3632)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3499)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3499)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3608)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3771)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2047)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1741)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1732)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2024)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:5105)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by KynoYang** [comment]
@hidroh Hi, sorry to bother you. I've been stuck by the same issue for a long time. Can I ask is there any side effects about the solution in #319 ?

**Comment by hidroh** [comment]
@KynoYang so far no problem for my use case, but it's an ugly `try-catch`. As [someone pointed out on reddit](https://www.reddit.com/r/androiddev/comments/4d2aje/ever_launched_a_fragmenttransaction_in_response/d1n9xhb), this seems to be a more general problem with message queue picking up messages when it should not.

**Comment by KynoYang** [comment]
@hidroh Thanks. The wired thing is that I can't reproduce it by myself. So far, your solution is the best one I've ever seen. Thank you very much!
