### ISSUE TITLE
BaseListFragment.java line 108

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#359]
#### in io.github.hidroh.materialistic.BaseListFragment.prepareOptionsMenu

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56a5ebdaf5d3a7f76b52b2d9](https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56a5ebdaf5d3a7f76b52b2d9)

**Comment by hidroh** [comment]
Full stacktrace:

```
Fatal Exception: java.lang.NullPointerException
       at io.github.hidroh.materialistic.BaseListFragment.prepareOptionsMenu(BaseListFragment.java:108)
       at io.github.hidroh.materialistic.BaseFragment.onPrepareOptionsMenu(BaseFragment.java:58)
       at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:2058)
       at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:2145)
       at android.support.v4.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:282)
       at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:477)
       at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:268)
       at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
       at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:550)
       at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onCreatePanelView(ToolbarActionBar.java:563)
       at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1240)
       at android.support.v7.app.AppCompatDelegateImplV7.onKeyDownPanel(AppCompatDelegateImplV7.java:1380)
       at android.support.v7.app.AppCompatDelegateImplV7.onKeyDown(AppCompatDelegateImplV7.java:903)
       at android.support.v7.app.AppCompatDelegateImplV7.dispatchKeyEvent(AppCompatDelegateImplV7.java:870)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1847)
       at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3701)
       at android.view.ViewRootImpl.deliverKeyEvent(ViewRootImpl.java:3626)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3161)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:124)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
