### ISSUE TITLE
SinglePageItemRecyclerViewAdapter.java line 146

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#361]
#### in io.github.hidroh.materialistic.widget.SinglePageItemRecyclerViewAdapter$1.onClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56a74339f5d3a7f76b58db7c](https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56a74339f5d3a7f76b58db7c)

**Comment by hidroh** [comment]
Full stacktrace:

```
Fatal Exception: java.lang.IllegalArgumentException: Invalid target position
       at android.support.v7.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:8859)
       at android.support.v7.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:6122)
       at android.support.v7.widget.LinearLayoutManager.smoothScrollToPosition(LinearLayoutManager.java:433)
       at android.support.v7.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1377)
       at io.github.hidroh.materialistic.widget.SinglePageItemRecyclerViewAdapter$1.onClick(SinglePageItemRecyclerViewAdapter.java:146)
       at android.view.View.performClick(View.java:5201)
       at android.view.View$PerformClick.run(View.java:21209)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5525)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by miannoumanshah** [comment]
@hidroh  did you resolve the issue because i am still facing the crush

**Comment by hidroh** [comment]
This was very long time ago so probably obsolete.
