### ISSUE TITLE
Preferences.java line 90

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#373]
#### in io.github.hidroh.materialistic.Preferences.isListItemCardView

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56bb8434f5d3a7f76bba6d8a](https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56bb8434f5d3a7f76bba6d8a)

**Comment by hidroh** [comment]
Full stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at android.support.v7.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:217)
       at android.support.v7.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:212)
       at io.github.hidroh.materialistic.Preferences.isListItemCardView(Preferences.java:90)
       at io.github.hidroh.materialistic.BaseListFragment$1.onSharedPreferenceChanged(BaseListFragment.java:43)
       at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:479)
       at android.app.SharedPreferencesImpl$EditorImpl.-wrap0(SharedPreferencesImpl.java)
       at android.app.SharedPreferencesImpl$EditorImpl$3.run(SharedPreferencesImpl.java:487)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
