### ISSUE TITLE
NPE when trying to set last updated time

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#394]
#### in io.github.hidroh.materialistic.BaseStoriesActivity$1.run

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56e81d9fffcdc04250da6bc1](https://fabric.io/ha-duy-trungs-projects/android/apps/io.github.hidroh.materialistic/issues/56e81d9fffcdc04250da6bc1)

**Comment by hidroh** [comment]
NPE when trying to set last updated time.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setSubtitle(java.lang.CharSequence)' on a null object reference
       at io.github.hidroh.materialistic.BaseStoriesActivity$1.run(BaseStoriesActivity.java:40)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6897)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
