### ISSUE TITLE
Saved article issue's 

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#484]
Tested saved articles in aeroplane mode. Seems to be a problem parsing many of them in 'Readability'. Downloading 'Comments' and 'Articles' doesn't seem to be working either. App has crashed several times in aeroplane mode also.
Device: LGE Nexus 4, SDK: 22, app version: 52

**Comment by hidroh** [comment]
Stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String io.github.hidroh.materialistic.data.Item.getText()' on a null object reference
       at io.github.hidroh.materialistic.WebFragment.onItemLoaded(WebFragment.java:171)
       at io.github.hidroh.materialistic.WebFragment.access$200(WebFragment.java:47)
       at io.github.hidroh.materialistic.WebFragment$ItemResponseListener.onResponse(WebFragment.java:192)
       at io.github.hidroh.materialistic.WebFragment$ItemResponseListener.onResponse(WebFragment.java:182)
       at io.github.hidroh.materialistic.data.HackerNewsClient$ItemCallbackWrapper.done(HackerNewsClient.java:304)
       at io.github.hidroh.materialistic.data.HackerNewsClient$ItemCallbackWrapper.onResponse(HackerNewsClient.java:279)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
