### ISSUE TITLE
Reduce saved state bundle size

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#572]
Lots of `TransactionTooLargeException` recently, happening to stories with a lot of comments (e.g. 150+ comments). Seem to affect only N/7 devices.

```
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 867924 bytes
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3752)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by android.os.TransactionTooLargeException: data parcel size 867924 bytes
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:615)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3606)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3744)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by hidroh** [comment]
Similar issue has been logged in AOSP bug tracker: http://b.android.com/212316
